# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='instaapp.Tag'),
        ),
    ]
