# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_auto_20160615_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
