# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0005_auto_20160616_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='instapp/uploads/photos'),
        ),
    ]
