# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0007_auto_20160616_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
