# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0012_auto_20160705_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='member',
        ),
        migrations.AddField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instaapp.Photo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instaapp.Member'),
        ),
    ]
